version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
    - checkout
    - run: cd web
    - restore_cache:
        key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
    - restore_cache:
        key: node-v1-{{ checksum "package.json" }}-{{ arch }}
    - run: yarn install
    - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules
       - persist_to_workspace:
          root: .
          paths:
            - node_modules
 test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run: cd web
      - restore_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
      - restore_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
      - run: yarn install
      - save_cache:
          key: yarn-v1-{{ checksum "yarn.lock" }}-{{ arch }}
          paths:
            - ~/.cache/yarn
      - save_cache:
          key: node-v1-{{ checksum "package.json" }}-{{ arch }}
          paths:
            - node_modules   
      - persist_to_workspace:
          root: .
          paths:
            - node_modules     

workflows:
  Build_and_Test:
    jobs:
      - build
      - test