version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "web/yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "web/package.json" }}-{{ arch }}

      - run: cd web && yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "web/yarn.lock" }}-{{ arch }}
          paths:
            - ~/web/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "web/package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ./web
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - restore_cache:
          key: yarn-v1-{{ checksum "web/yarn.lock" }}-{{ arch }}

      - restore_cache:
          key: node-v1-{{ checksum "web/package.json" }}-{{ arch }}

      - run: cd web && yarn install

      - save_cache:
          key: yarn-v1-{{ checksum "web/yarn.lock" }}-{{ arch }}
          paths:
            - ~/web/.cache/yarn

      - save_cache:
          key: node-v1-{{ checksum "web/package.json" }}-{{ arch }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: ./web
          paths:
            - node_modules
      
workflows:
  build_and_test:
    jobs:
      - build
      - test